services:
    # Auto-configure services in the bundle
    _defaults:
        autowire: true
        autoconfigure: true

    YIC\SluggableBundle\:
        resource: '../src/*'
        exclude: '../src/{Entity,DependencyInjection,Tests}'

    # Explicitly define the ParamConverter service
    YIC\SluggableBundle\Request\ParamConverter\SluggableParamConverter:
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: request.param_converter, priority: 10 }